/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Researchers;

import Controller.Researchers.BookListController;
import View.Components.BookPane;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import org.xml.sax.Attributes;

/**
 *
 * @author hylan
 */
public class ListOfStudents extends javax.swing.JInternalFrame {

    /**
     * Creates new form LivDis
     */
    
    private static BookPane selectedBookPane;
    
    
    private final BookListController controller; 
    
    public ListOfStudents() {
        
        initComponents();
        
        controller = new BookListController(this);
        
        controller.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelBookList = new javax.swing.JPanel();
        jLabelSearchIcon = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBookDetails = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldAuthor = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelName2 = new javax.swing.JLabel();
        jTextFieldName2 = new javax.swing.JTextField();
        jLabelStock2 = new javax.swing.JLabel();
        jLabelStock1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabelStock3 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelName4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelName1 = new javax.swing.JLabel();
        jTextFieldName1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelName3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabelName6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabelName7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabelName8 = new javax.swing.JLabel();
        jTextFieldName3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabelName9 = new javax.swing.JLabel();
        jLabelName10 = new javax.swing.JLabel();
        jTextFieldName4 = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelet = new javax.swing.JButton();
        jLabelImageBook = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Oásis - Livros Disponíveis ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearch.setText("Pesquisar Estudante:");
        getContentPane().add(jLabelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 390, -1));

        jPanelBookList.setLayout(new javax.swing.BoxLayout(jPanelBookList, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(jPanelBookList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 586, 453));
        getContentPane().add(jLabelSearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 55, 24));

        jPanelBookDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setText("Nome:");
        jPanelBookDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelName.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName.setText("Name");
        jPanelBookDetails.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 265, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setText("Classe:");
        jPanelBookDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setText("Escola:");
        jPanelBookDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setText("Turno:");
        jPanelBookDetails.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setText("Matricula:");
        jPanelBookDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setText("Curso:");
        jPanelBookDetails.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelAuthor.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelAuthor.setText("Name");
        jPanelBookDetails.add(jLabelAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 265, -1));

        jLabelStock.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelStock.setText("Name");
        jPanelBookDetails.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, -1));
        jPanelBookDetails.add(jTextFieldAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 270, -1));
        jPanelBookDetails.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 270, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel11.setText("Modulo:");
        jPanelBookDetails.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabelName2.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName2.setText("Name");
        jPanelBookDetails.add(jLabelName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 260, -1));
        jPanelBookDetails.add(jTextFieldName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 260, -1));

        jLabelStock2.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelStock2.setText("Name");
        jPanelBookDetails.add(jLabelStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 240, -1));

        jLabelStock1.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelStock1.setText("Name");
        jPanelBookDetails.add(jLabelStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 250, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelBookDetails.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelBookDetails.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelBookDetails.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 270, -1));

        jLabelStock3.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelStock3.setText("Name");
        jPanelBookDetails.add(jLabelStock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 250, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelBookDetails.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, -1));
        jPanelBookDetails.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 10));
        jPanelBookDetails.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 10));

        jTabbedPane1.addTab("Geral", jPanelBookDetails);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName4.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName4.setText("Name");
        jPanel1.add(jLabelName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 270, -1));

        jFormattedTextField1.setText("jFormattedTextField1");
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 260, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelName1.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName1.setText("Name");
        jPanel1.add(jLabelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 270, -1));
        jPanel1.add(jTextFieldName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelName3.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName3.setText("Name");
        jPanel1.add(jLabelName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, -1));

        jTabbedPane1.addTab("Contato", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel12.setText("CEP:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelName6.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName6.setText("Name");
        jPanel2.add(jLabelName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 270, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, -1));

        jLabelName7.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName7.setText("Name");
        jPanel2.add(jLabelName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 290, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel13.setText("Endereço:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jFormattedTextField2.setText("jFormattedTextField2");
        jPanel2.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 290, -1));

        jTabbedPane1.addTab("Endereço", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel14.setText("Login:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelName8.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName8.setText("Name");
        jPanel3.add(jLabelName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 270, -1));
        jPanel3.add(jTextFieldName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel15.setText("Senha:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelName9.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName9.setText("Name");
        jPanel3.add(jLabelName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, -1));

        jLabelName10.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelName10.setText("Name");
        jPanel3.add(jLabelName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, -1));
        jPanel3.add(jTextFieldName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 280, -1));

        jTabbedPane1.addTab("Conta", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 360, 280));

        jButtonUpdate.setText("Alterar");
        jButtonUpdate.setEnabled(false);
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 120, 40));

        jButtonDelet.setText("Deletar");
        getContentPane().add(jButtonDelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, -1, -1));

        jLabelImageBook.setText("Image");
        getContentPane().add(jLabelImageBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        controller.fastSearch();
    }//GEN-LAST:event_jTextFieldSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelImageBook;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelName10;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JLabel jLabelName4;
    private javax.swing.JLabel jLabelName6;
    private javax.swing.JLabel jLabelName7;
    private javax.swing.JLabel jLabelName8;
    private javax.swing.JLabel jLabelName9;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSearchIcon;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelStock1;
    private javax.swing.JLabel jLabelStock2;
    private javax.swing.JLabel jLabelStock3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBookDetails;
    private javax.swing.JPanel jPanelBookList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAuthor;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldName1;
    private javax.swing.JTextField jTextFieldName2;
    private javax.swing.JTextField jTextFieldName3;
    private javax.swing.JTextField jTextFieldName4;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables

    
    
    
}
